### ISSUE TITLE
Dependency on javax.servlet-api is not portable

### ISSUE THREAD

**Issue by barchetta** [microprofile-extensions/openapi-ext#15]
`swagger-ui` depends on ` javax.servlet-api` which is not part of the MicroProfile specification and therefore not supported by some MicroProfile implementations. This makes this project non-portable.

**Comment by phillip-kruger** [comment]
Yes. Happy to accept a PR if you find a way to do this without Servlet api. Thanks :)

**Comment by phillip-kruger** [comment]
Hi. Servlet API is removed in the latest version (v.1.1.0).
Also note the name changed to openapi-ui.

Please check. Thanks

**Comment by phillip-kruger** [comment]
Also note, it might that a while before this is available in maven central, build only happened now.
Thanks :)

**Comment by phillip-kruger** [comment]
Hi @barchetta 

This is now available in maven central.
Please test and let me know :

<dependency>
            <groupId>org.microprofile-ext.openapi-ext</groupId>
            <artifactId>openapi-ui</artifactId>
            <version>1.1.0</version>
            <scope>runtime</scope>
</dependency>

Thanks

**Comment by tjquinno** [comment]
I work with @barchetta and when I use the new extension (1.1.0) with Helidon MP it does not work.

I've attached a zip file containing a reproducer. Running the `mvn package` and then the `java` commands described at the beginning of the `README.md` file is all that's needed.

When running in Helidon MP -- which essentially runs a dedicated server per app, rather than a more traditional container -- it looks to me as if the `RequestInfo#getContextPath` method is returning an incorrect value. The `baseUri` value is `http://[0:0:0:0:0:0:0:1]:8080/` which leads to the method computing the context path as `"/"`. 

Later, when `contextRoot` is substituted in the templates it leads to URLs of the form `//webjars/...` which naturally fail.

If I use the debugger to force `Templates#getContextRoot` to set `contextRoot` to an empty string instead of `"/"` then things work.

[helidon-quickstart.zip](https://github.com/microprofile-extensions/openapi-ext/files/4201056/helidon-quickstart.zip)

**Comment by phillip-kruger** [comment]
Thanks @tjquinno - i'll fix and release a new version. Will let  you know once it's done. Should be later today

**Comment by phillip-kruger** [comment]
Hi @barchetta / @tjquinno 
Please test with 1.1.2 - Should be fixed.

Let me know, then I can close this.

**Comment by tjquinno** [comment]
Using 1.1.2 it is working now. Thanks for the quick turnaround.

**Comment by phillip-kruger** [comment]
Glad it's working, getting rid of servlet API was on the Todo for a long time. Glad it's done now
